language: R
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
  - r: release
  - r: devel
  allow_failures:
  - r: devel

branches:
  except:
  - dev

notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'